name = "RankedChoice"
uuid = "2dee5131-2512-436c-8d39-f34ee76c397d"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
